[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

remappings = [
    "forge-std/=lib/forge-std/src/",
    "chainlink/=lib/chainlink-brownie/"
]

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
base = "https://mainnet.base.org"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
